~ README (OK), mgit (OK)
Signed-off-by: Felix C. Stegerman <flx@obfusk.net>

diff --git a/mgit b/mgit
--- a/mgit
+++ b/mgit
@@ -2,7 +2,7 @@
 
 # --                                                            # {{{1
 #
-# File        : dev-scripts/mgit
+# File        : mgit
 # Maintainer  : Felix C. Stegerman <flx@obfusk.net>
 # Date        : 2012-06-27
 #
@@ -11,15 +11,14 @@
 #
 # --                                                            # }}}1
 
-function die () { echo "${2:-error}: $1" >&2; exit 1; }
-
-# --
-
 usage='mgit { {DIR,FIND,SUB} <dir> | {DIR,FIND,SUB}S <dir(s)> END'
 usage+=' | ENV | IN }'$'\n''            <git-cmd> [ <arg(s)> ]'
 
+function die () { echo "${2:-error}: $1" >&2; exit 1; }
+
 function fail () {
-  local x; for x in "$@"; do echo "error: $x" >&2; done
+  local x
+  for x in "$@"; do echo "error: $x" >&2; done
   die "$usage" usage
 }
 
@@ -29,11 +28,20 @@ args=(); git_dirs=(); git_args=()
 
 # --
 
-function get_one () { args=( "$1" ); shift; git_args=( "$@" ); }
+function git_args () {
+  [ "$#" -gt 0 ] || fail 'no git command'
+  git_args=( "$@" )
+}
+
+function get_one () {
+  [ "$#" -ge 1 ] || fail 'no dir'
+  args=( "$1" ); shift; git_args "$@"
+}
 
 function get_mny () {
   while [ "$#" -gt 0 -a "$1" != END ]; do args+=( "$1" ); shift; done
-  [ "$1" == END ] || fail 'no END'; shift; git_args=( "$@" )
+  [ "$1" == END ] || fail 'no END'
+  shift; git_args "$@"
 }
 
 # --
@@ -47,8 +55,8 @@ function get_sin () {
 function get_fnd () {
   [ "${#args[@]}" -gt 0 ] || fail 'no dirs to search'
 
-  get_sin < <(  find "${args[@]}" -name '.git' \
-                  | sed 's!/\.git$!!' | sort )
+  get_sin < \
+    <( find "${args[@]}" -name '.git' | sed 's!/\.git$!!' | sort )
 }
 
 function get_sub () {                                           # {{{1
@@ -69,13 +77,12 @@ function do_FS  () { get_mny "$@"; get_fnd; }
 function do_S   () { get_one "$@"; get_sub; }
 function do_SS  () { get_mny "$@"; get_sub; }
 
-function do_E   () { git_args=( "$@" ); git_dirs=( $MGIT_DIRS ); }
-function do_I   () { git_args=( "$@" ); get_sin; }
+function do_E   () { git_args "$@"; git_dirs=( $MGIT_DIRS ); }
+function do_I   () { git_args "$@"; get_sin; }
 
 # --
 
 [ "$#" -eq 0 -o "$1" == help ] && fail
-[ "$#" -ge 2 ] || fail 'not enough arguments'
 
 cmd="$1"; shift
 
@@ -86,14 +93,12 @@ else
   fail "unknown mgit command \`$cmd'"
 fi
 
-[ "${#git_args[@]}" -gt 0 ] || fail 'no git command'
-
 # --
 
 for d in "${git_dirs[@]}"; do
   echo "==> $d <=="
   pushd "$d" > /dev/null || die "failed to pushd $d"
-    echo git "${git_args[@]}"
+    git "${git_args[@]}"
   popd > /dev/null
   echo
 done
